create table "public"."games" (
    "id" bigint generated by default as identity not null,
    "home_team" bigint not null,
    "away_team" bigint not null,
    "start" timestamp with time zone not null,
    "home_team_spread" real,
    "away_team_spread" real,
    "over_under" real,
    "home_score" integer,
    "away_score" integer,
    "final" boolean default false
);


CREATE UNIQUE INDEX games_pkey ON public.games USING btree (id);

alter table "public"."games" add constraint "games_pkey" PRIMARY KEY using index "games_pkey";

alter table "public"."games" add constraint "games_away_team_fkey" FOREIGN KEY (away_team) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "games_away_team_fkey";

alter table "public"."games" add constraint "games_home_team_fkey" FOREIGN KEY (home_team) REFERENCES teams(id) ON DELETE CASCADE not valid;

alter table "public"."games" validate constraint "games_home_team_fkey";


