alter table "public"."picks" drop constraint "picks_account_fkey";

alter table "public"."picks" drop constraint "picks_game_fkey";

alter table "public"."picks" drop constraint "picks_pkey";

drop index if exists "public"."picks_pkey";

drop table "public"."picks";

create table "public"."spread_picks" (
    "id" bigint generated by default as identity not null,
    "account" uuid not null,
    "game" bigint not null,
    "content" json,
    "created_at" timestamp with time zone not null default now(),
    "successful" boolean,
    "selection" bigint not null,
    "spread" integer not null
);


CREATE UNIQUE INDEX picks_pkey ON public.spread_picks USING btree (id);

alter table "public"."spread_picks" add constraint "picks_pkey" PRIMARY KEY using index "picks_pkey";

alter table "public"."spread_picks" add constraint "spread_picks_account_fkey" FOREIGN KEY (account) REFERENCES accounts(user_id) not valid;

alter table "public"."spread_picks" validate constraint "spread_picks_account_fkey";

alter table "public"."spread_picks" add constraint "spread_picks_game_fkey" FOREIGN KEY (game) REFERENCES games(id) not valid;

alter table "public"."spread_picks" validate constraint "spread_picks_game_fkey";

alter table "public"."spread_picks" add constraint "spread_picks_selection_fkey" FOREIGN KEY (selection) REFERENCES teams(id) not valid;

alter table "public"."spread_picks" validate constraint "spread_picks_selection_fkey";


