create table "public"."communities" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "logo_url" text
);


alter table "public"."communities" enable row level security;

alter table "public"."accounts" add column "community" bigint;

CREATE UNIQUE INDEX communities_name_key ON public.communities USING btree (name);

CREATE UNIQUE INDEX communities_pkey ON public.communities USING btree (id);

alter table "public"."communities" add constraint "communities_pkey" PRIMARY KEY using index "communities_pkey";

alter table "public"."accounts" add constraint "accounts_community_fkey" FOREIGN KEY (community) REFERENCES communities(id) not valid;

alter table "public"."accounts" validate constraint "accounts_community_fkey";

alter table "public"."communities" add constraint "communities_name_key" UNIQUE using index "communities_name_key";


