create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "full_name" text not null,
    "city" text,
    "team_name" text not null,
    "abbreviation" text not null,
    "primary_logo_url" text not null
);


CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";


